name: SPARQL Query Submission
description: Form to submit SPARQL queries
title: "[Query] Short description of the query"
body:
  - type: input
    id: short_title
    attributes:
      label: Short title
      description: Provide a short title for your query.
      placeholder: "Short title"

  - type: textarea
    id: natural_language_query
    attributes:
      label: Query in natural language
      description: Describe in natural language what your query does. What are you trying to achieve with it?
      placeholder: "Describe your query here"

  - type: checkboxes
    id: predefined_sparql_endpoints
    attributes:
      label: Select SPARQL Endpoints
      description: Choose one or more SPARQL endpoints from the list, or select 'Other' to provide your own.
      options:
        - label: "Wikidata SPARQL (https://query.wikidata.org/sparql)"
        - label: "DBpedia SPARQL (https://dbpedia.org/sparql)"
        - label: "UniProt SPARQL (https://sparql.uniprot.org/sparql)"
        - label: "Other (please specify below)"

  - type: input
    id: custom_sparql_endpoint
    attributes:
      label: Custom SPARQL Endpoint
      description: If you selected 'Other' above, please provide the SPARQL endpoint here.
      placeholder: "https://example.org/sparql"

  - type: dropdown
    id: license
    attributes:
      label: License
      description: Select a license for your query submission. Click the links to read more about each license.
      options:
        - label: "MIT License (https://opensource.org/licenses/MIT)"
        - label: "Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0)"
        - label: "GPL 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)"
        - label: "CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)"
        - label: "CC0 (https://creativecommons.org/publicdomain/zero/1.0/)"
        - label: "Other (please specify below)"

  - type: input
    id: custom_license
    attributes:
      label: Custom License
      description: If you selected 'Other' above, please provide the license here.
      placeholder: "Enter your custom license"

  - type: input
    id: query_results_link
    attributes:
      label: Optional link to query results
      description: Add a link to the query results (optional).
      placeholder: "URL to the query results"
