name: SPARQL Query Submission
description: Form to submit SPARQL queries
title: "[Query] Short description of the query"
body:
  - type: input
    id: short_title
    attributes:
      label: Short title
      description: Provide a short title for your query.
      placeholder: "Short title"
      required: true

  - type: textarea
    id: natural_language_query
    attributes:
      label: Query in natural language
      description: Describe in natural language what your query does. What are you trying to achieve with it?
      placeholder: "Describe your query here"
      required: true

  - type: checkboxes
    id: sparql_endpoints
    attributes:
      label: SPARQL Endpoint(s)
      description: Add one or more SPARQL endpoints where this query works. Use the "+" symbol to add more endpoints.
      multiple: true
      placeholder: "https://example.org/sparql"
      required: true

  - type: input
    id: query_results_link
    attributes:
      label: Optional link to query results
      description: Add a link to the query results (optional).
      placeholder: "URL to the query results"
      required: false
