name: Convert SPARQL example to RDF

on:
  issues:
    types: [opened]

jobs:
  convert_to_rdf:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install rdflib  # If using rdflib for RDF processing

    - name: Convert issue to RDF
      run: |
        python scripts/convert_to_rdf.py
      env:
        GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
        GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
        GITHUB_ISSUE_URL: ${{ github.event.issue.html_url }}
        GITHUB_ISSUE_PRIORITY: ${{ github.event.issue.labels[0].name }}
