name: SPARQL Query Validation and RDF Conversion

# Grant permissions to write to issues
permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types: [opened]

jobs:
  validate_and_convert_to_rdf:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Updated to use v4 which supports Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to use v5 which supports Node.js 20
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install SPARQLWrapper rdflib

    # Step 1: Validate SPARQL query
    - name: Validate SPARQL query
      id: validate
      run: |
        python scripts/validate_sparql.py
      env:
        GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}

    # Step 2: Post comment on invalid query and close the issue
    - name: Post comment on invalid query and close the issue
      if: failure()
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        COMMENT_BODY="The SPARQL query you submitted is invalid. Please check the syntax and try again."
        gh api repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments -f body="$COMMENT_BODY"
        gh api repos/${{ github.repository }}/issues/${ISSUE_NUMBER} -X PATCH -f state="closed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Extract endpoint and license, apply labels
    - name: Extract Endpoint and License and Set Labels
      if: success()  # Only apply labels if the SPARQL validation was successful
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        
        # Extract endpoint from issue body
        ENDPOINT=$(echo "${{ github.event.issue.body }}" | awk -v RS='\r?\n' '/Select SPARQL Endpoints/{getline; print}' | tr -d '\r\n')
        
        # Extract license from issue body
        LICENSE=$(echo "${{ github.event.issue.body }}" | awk -v RS='\r?\n' '/License/{getline; print}' | tr -d '\r\n')
        
        # Apply the labels using the GitHub API (make sure they're passed as an array)
        if [[ -n "$ENDPOINT" ]] && [[ -n "$LICENSE" ]]; then
          gh api repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/labels \
          -f labels='["'"$ENDPOINT"'", "'"$LICENSE"'"]'
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Directly convert issue form to RDF with MD5 hash of SPARQL query
    - name: Convert issue form to RDF with MD5 hash
      if: success()  # Only run this step if the SPARQL validation was successful
      run: |
        python scripts/convert_form_to_rdf.py
      env:
        GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}

    # Step 5: Upload RDF as an artifact
    - name: Upload RDF as an artifact
      if: success()  # Only upload if the conversion was successful
      uses: actions/upload-artifact@v4
      with:
        name: issue-rdf-artifact
        path: issue_output.ttl
